title: Klimov Sergey
logo: "/images/logo.jpeg?raw=true"
description: >
  Golang Blockchain Engineer
  <br><br>
  I have been specializing in API design and service-oriented architecture for over 4 years. Since 2019, I have been developing blockchain platforms. Golang evangelist. I also teach course, speak at professional conferences, publish articles, and contribute to open-source projects.
theme: jekyll-theme-minimal
google_analytics: UA-165411420-1 # your Google Analytics tracking ID here
