title: Klimov Sergey
logo: "/images/logo.jpeg?raw=true"
description: >
  Senior Golang Developer (Blockchain)
  <br><br>
  I specialize in API design and service-oriented architecture.
  Now also a developer of blockchain platforms.
  I write articles, speak at conferences, and share my experiences with others.

theme: jekyll-theme-minimal
google_analytics: UA-165411420-1 # your Google Analytics tracking ID here
