title: Klimov Sergey # your name (or website title) here
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Golang Developer
  <br><br>
  2 years of development in PHP and the same in the Golang. Professional in writing the server side. More than six months in the development of the blockchain. I write articles, speak at conferences, I like to share experience with others.
  <br><br>
  <ul>
    <li><a href="https://t.me/klim0v">Telegram</a></li>
    <li><a href="https://github.com/klim0v">GitHub</a></li>
    <li><a href="https://habr.com/en/users/klim0v/">Habr</a></li>
    <li><a href="https://career.habr.com/klim0v">My circle</a></li>
    <li><a href="https://vk.com/klim0v">Vkontakte</a></li>
    <li><a href="https://www.facebook.com/klim0vsergey">Facebook</a></li>
    <li><a href="https://www.linkedin.com/in/klim0v/">LinkedIn</a></li>
    <li><a href="https://www.instagram.com/klim0vsergey/">Instagram</a></li>
    <li><a href="https://twitter.com/klim0vSergey">Twitter</a></li>
    <li><a href="mailto:klim0v-sergey@yandex.ru">klim0v-sergey@yandex.E-mail</a></li>
    <li><a href="tel:+79647700203">WhatsApp</a></li>
  </ul>
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-165411420-1 # your Google Analytics tracking ID here
