title: Klimov Sergey
logo: "/images/logo.jpeg?raw=true"
description: >
  Senior Golang Developer
  <br><br>
  Professional in writing the server-side with two years of development in PHP and the same in the Golang.
  More than six months of experience in blockchain development.
  I write articles, talk at conferences, and share my experience with others.

theme: jekyll-theme-minimal
google_analytics: UA-165411420-1 # your Google Analytics tracking ID here
