title: Klimov Sergey # your name (or website title) here
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Golang Developer
  <br><br>
  2 years of development in PHP and the same in the Golang. Professional in writing the server side. More than six months in the development of the blockchain. I write articles, speak at conferences, I like to share experience with others.
  <br><br>

  - LinkedIn: <a href="https://www.linkedin.com/in/klim0v/">klim0v</a>
  - My circle: <a href="https://career.habr.com/klim0v">klim0v</a>
  - Telephone: <a href="tel:+79647700203">+79647700203</a>
  - Telegram: <a href="https://t.me/klim0v">klim0v</a>
  - Vkontakte: <a href="https://vk.com/klim0v">klim0v</a>
  - Twitter: <a href="https://twitter.com/klim0vSergey">klim0vSergey</a>
  - Facebook: <a href="https://www.facebook.com/klim0vsergey">klim0vSergey</a>
  - E-mail: <a href="mailto:klim0v-sergey@yandex.ru">klim0v-sergey@yandex.ru</a>
  - Instagram: <a href="https://www.instagram.com/klim0vsergey/">klim0vSergey</a>
  - GitHub: <a href="https://github.com/klim0v">klim0v</a>

show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-165411420-1 # your Google Analytics tracking ID here
