title: Klimov Sergey # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://career.habr.com/klim0v">Мой Круг</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-165411420-1 # your Google Analytics tracking ID here
